<?xml version="1.0" encoding="utf-8"?>
<Database Name="AdventureWorks2008" Class="EmployeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSSQLSERVER4274;Initial Catalog=AdventureWorks2008;Integrated Security=True" SettingsObjectName="lab12.Properties.Settings" SettingsPropertyName="AdventureWorks2008ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="HumanResources.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Department_EmployeeDepartmentHistory" Member="EmployeeDepartmentHistories" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="EmployeeDepartmentHistory" />
    </Type>
  </Table>
  <Table Name="HumanResources.EmployeeDepartmentHistory" Member="EmployeeDepartmentHistories">
    <Type Name="EmployeeDepartmentHistory">
      <Column Name="BusinessEntityID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShiftID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Department_EmployeeDepartmentHistory" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Sales.SalesPerson" Member="SalesPersons">
    <Type Name="SalesPerson">
      <Column Name="BusinessEntityID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalesQuota" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Bonus" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CommissionPct" Type="System.Decimal" DbType="SmallMoney NOT NULL" CanBeNull="false" />
      <Column Name="SalesYTD" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SalesLastYear" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.lab12View" Member="lab12Views">
    <Type Name="lab12View">
      <Column Name="Name" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="DeparmentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessEntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>